# Generated by Django 5.2.17 on 2026-09-14 17:10

import cloudinary_storage.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester')], default='first', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('lecture_notes', 'Lecture Notes'), ('past_questions', 'Past Questions'), ('audio_file', 'Audio File'), ('video', 'Video'), ('external_link', 'External Link')], max_length=50)),
                ('image_file', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='image_resources/')),
                ('raw_file', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='raw_resources/')),
                ('video_file', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='video_resources/')),
                ('external_link', models.URLField(blank=True, null=True)),
                ('department', models.CharField(choices=[('computer_science', 'Computer Science'), ('software_engineering', 'Software Engineering'), ('mechanical_engineering', 'Mechanical Engineering'), ('electrical_engineering', 'Electrical Engineering'), ('english', 'English'), ('music', 'Music')], max_length=100)),
                ('faculty', models.CharField(choices=[('computing', 'Computing'), ('engineering', 'Engineering'), ('arts', 'Arts')], max_length=100)),
                ('level', models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level'), ('600', '600 Level')], max_length=3)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(default='Deleted User', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
