# Generated by Django 5.2.17 on 2026-09-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_resource_download_count_alter_resource_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
